### ISSUE TITLE
Add DB Support for PostGIS

### ISSUE THREAD

**Issue by tim-corley** [tim-corley/django-nextjs-geo-boilerplate#1]
Enable use of geographic / spatial data (i.e. latitude & longitude coordinates) in order to present maps on the client.

## Tasks 

- [x] Add Geocoder package
- [x] Install GDAL & GEOS to server container
- [x] Add GeoCoder API Key

## Resources

- https://docs.djangoproject.com/en/4.0/ref/contrib/gis/install/postgis/
- https://geocoder.readthedocs.io/api.html
- https://developer.mapquest.com/
